# [Info]
site_name: 刘清钧的个人网站 # 左上角标题
site_url: https://TracingOrigins.github.io
site_author: 刘清钧
site_description: 刘清钧的个人网站

# [Navigtion]
nav:
  - 博客:
    - BLOG/index.md
    - BLOG/others.md
    - CG:
      - Computer Graphics: BLOG/ComputerGraphics/cg-notes.md
      - GAMES101: BLOG/ComputerGraphics/games101.md
      - Blender: BLOG/ComputerGraphics/blender-notes.md
    - 游戏:
      - Unity: BLOG/Game/unity-notes.md
      - UE: BLOG/Game/ue-notes.md
      - 定义: BLOG/Game/what-is-game.md
      - 2D和3D: BLOG/Game/2d-vs-3d.md
    - 日语:
      - 笔记2/3: BLOG/Japanese/notes-2202-2203.md
      - 笔记4: BLOG/Japanese/notes-2204.md
      - 笔记5: BLOG/Japanese/notes-2205.md
      - 动词整理: BLOG/Japanese/verb.md
      - 形容词整理: BLOG/Japanese/adj.md
      - 名词整理: BLOG/Japanese/noun.md
      - 语法整理: BLOG/Japanese/grammar.md
      - 作文: BLOG/Japanese/essays.md
      - たんたんめん推特: BLOG/Japanese/tantanmen-translation.md
      - 中文日语: BLOG/Japanese/chinese.md
    - OS:
      - fork/exec/spawn: BLOG/OS/fork-exec-spawn.md
      - fork例: BLOG/OS/fork-example.md
    - Linux:
      - vim: BLOG/Linux/vim.md
      - tmux: BLOG/Linux/tmux.md
      - UNIX: BLOG/Linux/unix.md
      - 内核编译: BLOG/Linux/kernel-compile.md
      - 连接树莓派: BLOG/Linux/pi-start.md
    - macOS:
      - 使用tree命令和访达进行任务管理: BLOG/macOS/tree.md
      - 辅助功能缩放: BLOG/macOS/zoom.md
      - Mac与Android的文件传输: BLOG/macOS/sharing-mac-android.md
      - MAD制作流程: BLOG/macOS/mad.md
      - OBS开直播: BLOG/macOS/stream.md
    - 显示器:
      - BLOG//Display/sony-extend.md
    - UOS:
      - 相关链接: BLOG/UOS/links.md
    - Apple:
      - iPad购买建议: BLOG/Apple/ipad-recommend.md
      - Mac购买建议: BLOG/Apple/mac-recommend.md
    - GitHub:
      - 镜像到Gitee: BLOG/GitHub/mirror.md
    - Markdown:
      - Markdown语法初学习: BLOG/Markdown/grammars.md
      - MkDocs静态网站构建: BLOG/Markdown/mkdocs-site.md
      - mdBook静态网站构建: BLOG/Markdown/mdbook-site.md
      - GitHub Pages简介: BLOG/Markdown/github-pages.md
    - 电子工程:
      - Verilog仿真: BLOG/ElectronicEngineering/verilog-simulation.md
      - 各种存储器间的关系: BLOG/ElectronicEngineering/storage.md
      - 二阶线性时不变电路: BLOG/ElectronicEngineering/rlc.md
      - yosys尝试: BLOG/ElectronicEngineering/yosys-try.md
    - 基础:
      - 数学:
        - Latex简易符号: BLOG/Foundation/Math/latex.md
        - 线性代数笔记: BLOG/Foundation/Math/linear.md
        - 常用泰勒级数: BLOG/Foundation/Math/taylor.md
        - 最大似然估计: BLOG/Foundation/Math/max-pr.md
        - BLOG/Foundation/Math/sympy-det.md
      - 物理:
        - Gauss公式和Stokes公式: BLOG/Foundation/Physics/guass-stokes.md
        - 电磁学期末复习: BLOG/Foundation/Physics/electromagnetics.md
      - 网络:
        - 知识点总结: BLOG/Network/learning.md
        - 专有名词速查: BLOG/Network/nouns.md
        - GraphQL Hasura: BLOG/Network/graphql.md
      - 机器学习:
        - 动手学深度学习笔记: BLOG/Deeplearning/d2l.md
        - 语音识别笔记: BLOG/Deeplearning/speech-recognition.md
        - 数据加载优化: BLOG/Deeplearning/parallel-load.md
        - DDP:
          - DDP调研: BLOG/Deeplearning/ddp.md
          - ddp-note.py: BLOG/Deeplearning/ddp-note.md
    - 其他:
      - 视频信息初探: BLOG/Others/video-info.md
  - 开发:
    - DEV/index.md
    - App:
      - DEV/App/app-dev-sum.md
      - DEV/App/flutter-web-consideration.md
    - React:
      - DEV/React/notes.md
    - Flutter:
      - Notes: DEV/Flutter/notes.md
      - Dart linter: DEV/Flutter/dart-lint.md
      - Template: DEV/Flutter/template.md
      - State Management: DEV/Flutter/state-management.md
      - Packages: DEV/Flutter/common-packages.md
    - Xcode:
      - 新建开发模块: DEV/Xcode/scheme-dev.md
      - Markup Syntax: DEV/Xcode/markup.md
      - 新建文件注释: DEV/Xcode/file-header.md
      - 常用快捷键: DEV/Xcode/shortcuts.md
      - Set Build Number: DEV/Xcode/set-build-number.md
      - Crash Analysis: DEV/Xcode/crash-analysis.md
    - SwiftUI:
      - Data Essentials: DEV/SwiftUI/data-essentials.md
    - AppKit:
      - 纯代码创建项目: DEV/AppKit/programmatically.md
      - 苹果平台应用开发之路: DEV/AppKit/road.md
    - 编程:
      - 推荐的学习路线: DEV/Programming/recommendation.md
      - 我对编程语言的感受: DEV/Programming/my-feelings.md
      - Dart:
        - 学习笔记: DEV/Programming/Dart/learning.md
      - Swift:
        - 学习资源: DEV/Programming/Swift/learning-resources.md
        - 基础语法笔记: DEV/Programming/Swift/notes-basic-grammars.md
        - WORKING LanguageGuide笔记: DEV/Programming/Swift/notes-language-guide.md
        - WORKING 常用标准库函数笔记: DEV/Programming/Swift/notes-useful-foundation.md
        - 教学作业: DEV/Programming/Swift/lecture-homework.md
        - 并行计算: DEV/Programming/Swift/parallel-for.md
      - Python:
        - 不喜欢Python的理由: DEV/Programming/Python/dislike.md
        - 复制拷贝: DEV/Programming/Python/copy.md
        - numpy速查表: DEV/Programming/Python/numpy-overview.md
      - C:
        - 笔记整理: DEV/Programming/C/review.md
        - 常用函数: DEV/Programming/C/final.md
        - stdout按行刷新: DEV/Programming/C/stdout-fflush.md
        - 二维数组调试: DEV/Programming/C/watch-matrix.md
      - C#:
        - 学习笔记: DEV/Programming/Csharp/learning.md
      - C++:
        - 1 C++的几个基本问题: DEV/Programming/Cpp/1.md
        - 2 函数重载: DEV/Programming/Cpp/2.md
        - 3 类: DEV/Programming/Cpp/3.md
        - 4 操作符重载: DEV/Programming/Cpp/4.md
        - 5 类的继承与派生: DEV/Programming/Cpp/5.md
        - 6 模版: DEV/Programming/Cpp/6.md
        - 7 异常处理: DEV/Programming/Cpp/7.md
        - 8 流类库的输入与输出: DEV/Programming/Cpp/8.md
        - List: DEV/Programming/Cpp/list.md
        - Stack: DEV/Programming/Cpp/stack.md
        - 类数据成员: DEV/Programming/Cpp/class-properties.md
        - Google风格: DEV/Programming/Cpp/google-format.md
        - 考试复习: DEV/Programming/Cpp/final.md
        - OJ技巧和策略: DEV/Programming/Cpp/oj.md
      - MATLAB:
        - MATLAB入门: DEV/Programming/MATLAB/tour.md
        - 抛硬币的涨落问题: DEV/Programming/MATLAB/coin.md
        - 命令行MATLAB: DEV/Programming/MATLAB/terminal-matlab.md
    - ExNotes:
      - ExNotes设计文档: DEV/ExNotes/design.md
      - ExNotes开发考量: DEV/ExNotes/learning.md
  - 转载:
    - REPRODUCE/index.md
    - REPRODUCE/how-to-ask-questions-the-smart-way.md
    - REPRODUCE/tim-cook-at-duke.md
    - REPRODUCE/my-best-teacher.md
  - 我:
    - ME/index.md
    - 个人简介: ME/me.md
    - 关于爱情: ME/love.md
    - 支持作者: ME/support.md
  - 网站:
    - WEBSITE/index.md # 访客打开网站第一个看到的是 docs/index.md（会报错 The following pages exist in the docs directory, but are not included in the "nav" configuration: index.md 不要紧）  如果访客之后想要重新看到这个界面  可以在 docs/WEBSITE/index.md 找到
    - 网站构建: WEBSITE/build.md
    - 文章编写帮助: WEBSITE/help.md
    - 测试文档: WEBSITE/test.md

# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/TracingOrigins/TracingOrigins.github.io # 右上角点击跳转的链接
repo_name: TracingOrigins.github.io # 右上角的名字
## [bottom-left corner]
copyright: 刘清钧 CC-BY-4.0 # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/381756723
      name: Bilibili | TracingOrigins # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/TracingOrigins
      name: GitHub | TracingOrigins

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
